package Vistas;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AlquileresUI extends javax.swing.JPanel {

    /**
     * Creates new form AlquileresUI
     */
    public AlquileresUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEjemplares = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        jtEjemplares = new javax.swing.JTable();
        jbAgregarPelicula = new javax.swing.JButton();
        jbBuscarCliente1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRegistrarAlquiler = new javax.swing.JPanel();
        jlCliente = new javax.swing.JLabel();
        jtfCliente = new javax.swing.JTextField();
        jbBuscarCliente = new javax.swing.JButton();
        panelAlquileresNoDevueltos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEjemplaresPendientes = new javax.swing.JTable();

        jtEjemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsp.setViewportView(jtEjemplares);

        jbAgregarPelicula.setText("Agregar Pelicula");

        jbBuscarCliente1.setText("Buscar");

        jTextField2.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de la película");

        javax.swing.GroupLayout jpEjemplaresLayout = new javax.swing.GroupLayout(jpEjemplares);
        jpEjemplares.setLayout(jpEjemplaresLayout);
        jpEjemplaresLayout.setHorizontalGroup(
            jpEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEjemplaresLayout.createSequentialGroup()
                        .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jbAgregarPelicula))
                    .addGroup(jpEjemplaresLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscarCliente1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEjemplaresLayout.setVerticalGroup(
            jpEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEjemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarCliente1))
                .addGap(20, 20, 20)
                .addGroup(jpEjemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAgregarPelicula)
                    .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        setMaximumSize(new java.awt.Dimension(750, 380));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(750, 380));

        jlCliente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlCliente.setText("Cliente");

        jtfCliente.setEditable(false);
        jtfCliente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jbBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbBuscarCliente.setText("Buscar");

        javax.swing.GroupLayout panelRegistrarAlquilerLayout = new javax.swing.GroupLayout(panelRegistrarAlquiler);
        panelRegistrarAlquiler.setLayout(panelRegistrarAlquilerLayout);
        panelRegistrarAlquilerLayout.setHorizontalGroup(
            panelRegistrarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarCliente)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        panelRegistrarAlquilerLayout.setVerticalGroup(
            panelRegistrarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistrarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCliente)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarCliente))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Alquiler", panelRegistrarAlquiler);

        panelAlquileresNoDevueltos.setName("No Devueltos");

        jtEjemplaresPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtEjemplaresPendientes);

        javax.swing.GroupLayout panelAlquileresNoDevueltosLayout = new javax.swing.GroupLayout(panelAlquileresNoDevueltos);
        panelAlquileresNoDevueltos.setLayout(panelAlquileresNoDevueltosLayout);
        panelAlquileresNoDevueltosLayout.setHorizontalGroup(
            panelAlquileresNoDevueltosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquileresNoDevueltosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAlquileresNoDevueltosLayout.setVerticalGroup(
            panelAlquileresNoDevueltosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquileresNoDevueltosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Peliculas Pendientes", panelAlquileresNoDevueltos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("No Devueltos");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbAgregarPelicula;
    private javax.swing.JButton jbBuscarCliente;
    private javax.swing.JButton jbBuscarCliente1;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JPanel jpEjemplares;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable jtEjemplares;
    private javax.swing.JTable jtEjemplaresPendientes;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JPanel panelAlquileresNoDevueltos;
    private javax.swing.JPanel panelRegistrarAlquiler;
    // End of variables declaration//GEN-END:variables
}
