package Vistas;

import Controladores.BonoController;
import Controladores.ClienteController;
import Modelo.Bono;
import Modelo.Cliente;
import javax.swing.JOptionPane;
import videoclub.Controladores;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ComprarBonoUI extends javax.swing.JPanel {

    private ClienteController clienteController;
    private BonoController bonoController;
    private Cliente cliente;

    /**
     * Creates new form ComprarBonoUI
     */
    public ComprarBonoUI() {
        initComponents();
        clienteController = Controladores.clienteController;
        bonoController = Controladores.bonoController;
        cliente = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jpCenter = new javax.swing.JPanel();
        etiquetaPrimerPaso = new javax.swing.JLabel();
        etiquetaCliente = new javax.swing.JLabel();
        etiquetaSegundoPaso = new javax.swing.JLabel();
        etiquetaDni = new javax.swing.JLabel();
        botonComprarBono = new javax.swing.JButton();
        botonBuscarCliente = new javax.swing.JButton();
        listaBonos = new javax.swing.JComboBox();
        campoDniCliente = new javax.swing.JFormattedTextField();
        etiquetaPrecioBono = new javax.swing.JLabel();
        campoPrecioBono = new javax.swing.JLabel();
        campoCliente = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(750, 380));
        setMinimumSize(new java.awt.Dimension(750, 380));
        setLayout(new java.awt.BorderLayout());

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Comprar Bono");
        add(jlTitulo, java.awt.BorderLayout.PAGE_START);

        jpCenter.setMaximumSize(new java.awt.Dimension(750, 355));
        jpCenter.setMinimumSize(new java.awt.Dimension(750, 355));

        etiquetaPrimerPaso.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        etiquetaPrimerPaso.setText("1° Ingrese el DNI del cliente y pulse el botón Buscar Cliente");

        etiquetaCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaCliente.setText("Cliente");

        etiquetaSegundoPaso.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        etiquetaSegundoPaso.setText("2° Seleccione el periodo del bono");

        etiquetaDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaDni.setText("DNI");

        botonComprarBono.setText("Comprar Bono");
        botonComprarBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarBonoActionPerformed(evt);
            }
        });

        botonBuscarCliente.setText("Buscar Cliente");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        listaBonos.setModel(new Vistas.modelos.BonoComboBoxModel());

        campoDniCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("########"))));

        etiquetaPrecioBono.setText("Precio bono");

        campoPrecioBono.setBackground(new java.awt.Color(255, 255, 255));
        campoPrecioBono.setOpaque(true);

        campoCliente.setBackground(new java.awt.Color(255, 255, 255));
        campoCliente.setOpaque(true);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCenterLayout = new javax.swing.GroupLayout(jpCenter);
        jpCenter.setLayout(jpCenterLayout);
        jpCenterLayout.setHorizontalGroup(
            jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCenterLayout.createSequentialGroup()
                .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCenterLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaDni)
                            .addComponent(etiquetaCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCenterLayout.createSequentialGroup()
                                .addComponent(campoDniCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBuscarCliente))
                            .addComponent(campoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiquetaPrimerPaso))
                    .addGroup(jpCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaSegundoPaso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpCenterLayout.createSequentialGroup()
                                    .addComponent(etiquetaPrecioBono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoPrecioBono, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(listaBonos, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpCenterLayout.createSequentialGroup()
                                    .addComponent(botonComprarBono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonCancelar))))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jpCenterLayout.setVerticalGroup(
            jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaPrimerPaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDni)
                    .addComponent(botonBuscarCliente)
                    .addComponent(campoDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCliente)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(etiquetaSegundoPaso)
                .addGap(18, 18, 18)
                .addComponent(listaBonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoPrecioBono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPrecioBono, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprarBono)
                    .addComponent(botonCancelar))
                .addGap(128, 128, 128))
        );

        add(jpCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        try {
            cliente = clienteController.buscarClientePorDni(((Number) campoDniCliente.getValue()).longValue());
            campoCliente.setText(cliente.getApellido()+" "+cliente.getNombre());
        } catch(NullPointerException exc) {
            JOptionPane.showMessageDialog(null,
                    "No existe ningun cliente con el numero de DNI ingresado.",
                    "Error Cliente",
                    JOptionPane.ERROR_MESSAGE);
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void botonComprarBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarBonoActionPerformed
        try {
            if(cliente != null)
                if(listaBonos.getSelectedItem() != null) {
                    clienteController.comprarBono(cliente, (Bono) listaBonos.getSelectedItem());
                    limpiarCampos();
                    JOptionPane.showMessageDialog(null, "Se ha completado la operación correctamente", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                    throw new Exception("No ha seleccionado ningún bono");
            else
                throw new Exception("No ha seleccionado ningún cliente");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonComprarBonoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonComprarBono;
    private javax.swing.JLabel campoCliente;
    private javax.swing.JFormattedTextField campoDniCliente;
    private javax.swing.JLabel campoPrecioBono;
    private javax.swing.JLabel etiquetaCliente;
    private javax.swing.JLabel etiquetaDni;
    private javax.swing.JLabel etiquetaPrecioBono;
    private javax.swing.JLabel etiquetaPrimerPaso;
    private javax.swing.JLabel etiquetaSegundoPaso;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpCenter;
    private javax.swing.JComboBox listaBonos;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoDniCliente.setValue(0);
        campoCliente.setText("");
        campoPrecioBono.setText("");
        listaBonos.setSelectedItem(null);
        listaBonos.updateUI();
        cliente = null;
    }

}
