package Vistas;

import Controladores.PeliculaController;
import Modelo.Pelicula;
import Vistas.modelos.EjemplaresPeliculaTableModel;
import javax.swing.JOptionPane;
import videoclub.Controladores;
import videoclub.VideoclubApp;

/**
 *
 * @author Mauro Federico Lopez
 */
public class EjemplarUI extends javax.swing.JPanel {

    private PeliculaController controlador;
    private Pelicula pelicula;

    /**
     * Creates new form EjemplarUI
     */
    public EjemplarUI() {
        initComponents();
        controlador = Controladores.peliculaController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tablaEjemplares = new javax.swing.JTable();
        campoCodigoPelicula = new javax.swing.JLabel();
        campoTituloPelicula = new javax.swing.JLabel();
        campoGeneroPelicula = new javax.swing.JLabel();
        botonEliminarEjemplar = new javax.swing.JButton();
        campoAño = new javax.swing.JLabel();
        campoDuracion = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        campoSinopsis = new javax.swing.JTextPane();
        botonAgregar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaCreditoAlquiler = new javax.swing.JLabel();
        campoCreditoAlquiler = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(750, 380));
        setMinimumSize(new java.awt.Dimension(750, 380));
        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Datos de Película");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        panelDatos.setMaximumSize(new java.awt.Dimension(567, 351));
        panelDatos.setMinimumSize(new java.awt.Dimension(567, 351));

        tablaEjemplares.setAutoCreateRowSorter(true);
        tablaEjemplares.setModel(new Vistas.modelos.EjemplaresPeliculaTableModel());
        tablaEjemplares.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaEjemplares);

        campoCodigoPelicula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCodigoPelicula.setText("jLabel1");

        campoTituloPelicula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoTituloPelicula.setText("jLabel2");

        campoGeneroPelicula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoGeneroPelicula.setText("jLabel3");

        botonEliminarEjemplar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonEliminarEjemplar.setText("Eliminar Ejemplar");
        botonEliminarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEjemplarActionPerformed(evt);
            }
        });

        campoAño.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoAño.setText("jLabel2");

        campoDuracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoDuracion.setText("jLabel2");

        campoSinopsis.setEditable(false);
        campoSinopsis.setOpaque(false);
        jScrollPane.setViewportView(campoSinopsis);

        botonAgregar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        etiquetaCreditoAlquiler.setText("Crédito Alquiler");

        campoCreditoAlquiler.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar nuevo ejemplar");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoTituloPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCodigoPelicula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEliminarEjemplar)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(campoGeneroPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                .addComponent(botonAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                .addComponent(etiquetaCreditoAlquiler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCreditoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addComponent(campoCodigoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(campoTituloPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoGeneroPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoAño)
                    .addComponent(campoDuracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarEjemplar))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaCreditoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCreditoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAgregar)
                            .addComponent(botonCancelar))))
                .addGap(16, 16, 16))
        );

        add(panelDatos, java.awt.BorderLayout.CENTER);

        botonVolver.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEjemplarActionPerformed
        try {
            int[] indices = tablaEjemplares.getSelectedRows();
            if(indices.length > 0) {
                controlador.eliminarEjemplar(pelicula, indices);
            }
            else
                throw new Exception("No ha seleccionado ningun ejemplar para eliminar");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarEjemplarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        VideoclubApp.principal.agregarComponenteAlCentro(new PeliculaUI());
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        Integer creditoAlquiler = ((Number) campoCreditoAlquiler.getValue()).intValue();
        controlador.registrarNuevoEjemplar(pelicula, creditoAlquiler);
        limpiarCampos();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminarEjemplar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel campoAño;
    private javax.swing.JLabel campoCodigoPelicula;
    private javax.swing.JFormattedTextField campoCreditoAlquiler;
    private javax.swing.JLabel campoDuracion;
    private javax.swing.JLabel campoGeneroPelicula;
    private javax.swing.JTextPane campoSinopsis;
    private javax.swing.JLabel campoTituloPelicula;
    private javax.swing.JLabel etiquetaCreditoAlquiler;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTable tablaEjemplares;
    // End of variables declaration//GEN-END:variables

    /**
     * @param pelicula the pelicula to set
     */
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
        ((EjemplaresPeliculaTableModel) tablaEjemplares.getModel()).setPelicula(pelicula);
        campoCodigoPelicula.setText("Código: " + pelicula.getCodigo());
        campoTituloPelicula.setText("Título: " + pelicula.getTitulo());
        campoGeneroPelicula.setText("Género: " + pelicula.getGenero().toString());
        campoAño.setText("Año: " + pelicula.getAño().toString());
        campoDuracion.setText("Duración: " + pelicula.getMinDuracion().toString() + " min");
        campoSinopsis.setText("Sinopsis: " + pelicula.getSinopsis());
    }

    private void limpiarCampos() {
        campoCreditoAlquiler.setValue(0);
    }
}
