package Vistas;

import Controladores.FacturacionController;
import videoclub.Controladores;

/**
 *
 * @author Mauro Federico Lopez
 */
public class FacturacionMensualUI extends javax.swing.JPanel {

    private FacturacionController controlador;

    /**
     * Creates new form FacturacionMensualUI
     */
    public FacturacionMensualUI() {
        initComponents();
        controlador = Controladores.facturacionController;
        campoIngresosPorBonos.setText("Ingresos de venta de bonos de los ultimos 30 dias:   $" + controlador.ingresosMensual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        campoIngresosPorBonos = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(750, 380));
        setMinimumSize(new java.awt.Dimension(750, 380));
        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Facturación Mensual");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        campoIngresosPorBonos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoIngresosPorBonos.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoIngresosPorBonos, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoIngresosPorBonos)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoIngresosPorBonos;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
