package Vistas;

import Controladores.PeliculaController;
import Modelo.Genero;
import Modelo.Pelicula;
import Vistas.modelos.GeneroComboBoxModel;
import java.text.DecimalFormat;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import videoclub.Controladores;

/**
 *
 * @author Mauro Federico Lopez
 */
public class PeliculaUI extends javax.swing.JPanel {

    private PeliculaController controlador;

    public PeliculaUI() {
        initComponents();
        controlador = Controladores.peliculaController;

        TableColumn columnaAño = tablaPeliculas.getColumnModel().getColumn(2);
        columnaAño.setCellEditor(new DefaultCellEditor(new JFormattedTextField(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("####"))))));
        TableColumn columnaDuracion = tablaPeliculas.getColumnModel().getColumn(3);
        columnaDuracion.setCellEditor(new DefaultCellEditor(new JFormattedTextField(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("###"))))));
        TableColumn columnaGenero = tablaPeliculas.getColumnModel().getColumn(5);
        columnaGenero.setCellEditor(new DefaultCellEditor(new JComboBox(new GeneroComboBoxModel())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        botonEliminarPelicula = new javax.swing.JButton();
        botonVerEjemplares = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        etiquetaCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        etiquetaTitulo = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        etiquetaAño = new javax.swing.JLabel();
        campoAño = new javax.swing.JFormattedTextField();
        etiquetaDuracion = new javax.swing.JLabel();
        campoMinutoDuracion = new javax.swing.JFormattedTextField();
        etiquetaMinutoDuracion = new javax.swing.JLabel();
        etiquetaGenero = new javax.swing.JLabel();
        campoGenero = new javax.swing.JComboBox();
        etiquetaSinopsis = new javax.swing.JLabel();
        jspSinopsis = new javax.swing.JScrollPane();
        campoSinopsis = new javax.swing.JTextArea();
        botonAgregar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaPeliculas = new javax.swing.JLabel();
        jsp = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1050, 530));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setName("");
        setPreferredSize(new java.awt.Dimension(617, 0));
        setLayout(new java.awt.BorderLayout());

        botonEliminarPelicula.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonEliminarPelicula.setText("Eliminar Pelicula");
        botonEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPeliculaActionPerformed(evt);
            }
        });

        botonVerEjemplares.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonVerEjemplares.setText("Ver Ejemplares");
        botonVerEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerEjemplaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(botonEliminarPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerEjemplares)
                .addGap(0, 542, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonEliminarPelicula)
                .addComponent(botonVerEjemplares))
        );

        add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelDatos.setMaximumSize(new java.awt.Dimension(206, 330));
        panelDatos.setMinimumSize(new java.awt.Dimension(206, 330));
        panelDatos.setPreferredSize(new java.awt.Dimension(206, 330));

        etiquetaCodigo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaCodigo.setText("Código");

        campoCodigo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaTitulo.setText("Titulo");

        campoTitulo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        etiquetaAño.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaAño.setText("Año");

        campoAño.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        etiquetaDuracion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaDuracion.setText("Duración");

        campoMinutoDuracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        etiquetaMinutoDuracion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaMinutoDuracion.setText("minutos");

        etiquetaGenero.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaGenero.setText("Genero");

        campoGenero.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoGenero.setModel(new Vistas.modelos.GeneroComboBoxModel());

        etiquetaSinopsis.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaSinopsis.setText("Sinopsis");

        campoSinopsis.setColumns(20);
        campoSinopsis.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoSinopsis.setRows(5);
        campoSinopsis.setEnabled(false);
        jspSinopsis.setViewportView(campoSinopsis);

        botonAgregar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(etiquetaSinopsis)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaCodigo)
                                    .addComponent(etiquetaTitulo))
                                .addGap(33, 33, 33)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(campoTitulo)))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(botonAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar))
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelDatosLayout.createSequentialGroup()
                                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(etiquetaAño)
                                        .addComponent(etiquetaDuracion)
                                        .addComponent(etiquetaGenero))
                                    .addGap(25, 25, 25)
                                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(panelDatosLayout.createSequentialGroup()
                                            .addComponent(campoMinutoDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(etiquetaMinutoDuracion))
                                        .addComponent(campoAño)
                                        .addComponent(campoGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jspSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigo)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTitulo)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaAño)
                    .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDuracion)
                    .addComponent(etiquetaMinutoDuracion)
                    .addComponent(campoMinutoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jspSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonCancelar))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        add(panelDatos, java.awt.BorderLayout.LINE_END);

        etiquetaPeliculas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaPeliculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPeliculas.setText("Peliculas");
        add(etiquetaPeliculas, java.awt.BorderLayout.PAGE_START);

        tablaPeliculas.setAutoCreateRowSorter(true);
        tablaPeliculas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablaPeliculas.setModel(new Vistas.modelos.PeliculaTableModel());
        tablaPeliculas.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaPeliculas);

        add(jsp, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        try {
            String codigo = campoCodigo.getText();
            if(controlador.codigoPeliculaValido(codigo))
                if(campoGenero.getSelectedItem() != null) {
                    String titulo = campoTitulo.getText();
                    Long año = ((Number)campoAño.getValue()).longValue();
                    Long minutoDuracion = ((Number) campoMinutoDuracion.getValue()).longValue();
                    Genero genero = (Genero) campoGenero.getSelectedItem();
                    String sinopsis = campoSinopsis.getText();
                    controlador.registrarNuevaPelicula(new Pelicula(codigo, titulo, año, minutoDuracion, genero, sinopsis));
                }
                else
                    throw new Exception("No ha seleccionado un genero para la pelicula");
            else
                throw new Exception("El código de la película ya está registrado");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPeliculaActionPerformed
        try {
            int[] indices = tablaPeliculas.getSelectedRows();
            if(indices.length > 0) {
                controlador.eliminarPelicula(indices);
            }
            else
                throw new Exception("No ha seleccionado ninguna película para eliminar");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarPeliculaActionPerformed

    private void botonVerEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerEjemplaresActionPerformed
        try {
            int indice = tablaPeliculas.getSelectedRow();
            if(indice >= 0) {
                Pelicula pelicula = controlador.obtenerPelicula(indice);
            }
            else
                throw new Exception("No ha seleccionado ninguna película para ver sus ejemplares");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonVerEjemplaresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminarPelicula;
    private javax.swing.JButton botonVerEjemplares;
    private javax.swing.JFormattedTextField campoAño;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JComboBox campoGenero;
    private javax.swing.JFormattedTextField campoMinutoDuracion;
    private javax.swing.JTextArea campoSinopsis;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel etiquetaAño;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaDuracion;
    private javax.swing.JLabel etiquetaGenero;
    private javax.swing.JLabel etiquetaMinutoDuracion;
    private javax.swing.JLabel etiquetaPeliculas;
    private javax.swing.JLabel etiquetaSinopsis;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JScrollPane jspSinopsis;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTable tablaPeliculas;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoCodigo.setText("");
        campoTitulo.setText("");
        campoSinopsis.setText("");
        campoAño.setValue(0);
        campoMinutoDuracion.setValue(0);
        campoGenero.setSelectedItem(null);
        campoGenero.updateUI();
    }

}
