package Vistas;

import Controladores.FacturacionController;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import videoclub.Controladores;

/**
 *
 * @author Mauro Federico Lopez
 */
public class RecargoSancionUI extends javax.swing.JPanel implements Observer {

    private FacturacionController controlador;

    /**
     * Creates new form RecargoSancionUI
     */
    public RecargoSancionUI() {
        initComponents();
        controlador = Controladores.facturacionController;
        controlador.addObserver(this);
        campoRecargo.setValue(controlador.obtenerRecargo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonModificarValorRecargo = new javax.swing.JButton();
        campoRecargo = new javax.swing.JFormattedTextField();
        etiquetaRecargo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Recargo de las sanciones");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        botonModificarValorRecargo.setText("Modificar Valor Recargo");
        botonModificarValorRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarValorRecargoActionPerformed(evt);
            }
        });

        campoRecargo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        etiquetaRecargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaRecargo.setText("Recargo");

        jTextPane1.setBorder(null);
        jTextPane1.setText("  Para modificar el valor de recargo de los ejemplares devueltos fuera de plazo, sólo modifique el valor y presione el botón \"Modificar Valor Recargo\". Luego este valor será una constante para calcular la sanción de los ejemplares devueltos fuera de plazo y se asignarán al cliente correspondiente");
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaRecargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarValorRecargo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaRecargo)
                    .addComponent(campoRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarValorRecargo))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarValorRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarValorRecargoActionPerformed
        try {
            controlador.modificarRecargo(((Number)campoRecargo.getValue()).doubleValue());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonModificarValorRecargoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarValorRecargo;
    private javax.swing.JFormattedTextField campoRecargo;
    private javax.swing.JLabel etiquetaRecargo;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        campoRecargo.setText(String.valueOf(controlador.obtenerRecargo()));
    }

}
