package Vistas;

import Controladores.ClienteController;
import Modelo.Cliente;
import Modelo.Sancion;
import Vistas.modelos.SancionTableModel;
import java.util.ArrayList;
import videoclub.Controladores;
import videoclub.VideoclubApp;

/**
 *
 * @author Mauro Federico Lopez
 */
public class SancionUI extends javax.swing.JPanel {

    private ClienteController controlador;
    private Cliente cliente;

    /**
     * Creates new form SancionUI
     */
    public SancionUI() {
        initComponents();
        controlador = Controladores.clienteController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        panelSancionesCliente = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tablaSanciones = new javax.swing.JTable();
        botonCancelarSancion = new javax.swing.JButton();
        campoNombreCliente = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(750, 380));
        setMinimumSize(new java.awt.Dimension(750, 380));
        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Sanciones");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        tablaSanciones.setModel(new Vistas.modelos.SancionTableModel());
        tablaSanciones.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaSanciones);

        botonCancelarSancion.setText("Cancelar Sanción");
        botonCancelarSancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarSancionActionPerformed(evt);
            }
        });

        campoNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNombreCliente.setText("jLabel1");

        javax.swing.GroupLayout panelSancionesClienteLayout = new javax.swing.GroupLayout(panelSancionesCliente);
        panelSancionesCliente.setLayout(panelSancionesClienteLayout);
        panelSancionesClienteLayout.setHorizontalGroup(
            panelSancionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSancionesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSancionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSancionesClienteLayout.createSequentialGroup()
                        .addGroup(panelSancionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCancelarSancion))
                        .addGap(0, 245, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSancionesClienteLayout.setVerticalGroup(
            panelSancionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSancionesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelarSancion)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        add(panelSancionesCliente, java.awt.BorderLayout.CENTER);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarSancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarSancionActionPerformed
        Sancion sancion = ((SancionTableModel) tablaSanciones.getModel()).obtenerFecha(tablaSanciones.getSelectedRow());
        controlador.cancelarSancion(sancion);
        setCliente(cliente);
    }//GEN-LAST:event_botonCancelarSancionActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        VideoclubApp.principal.agregarComponenteAlCentro(new ClienteUI());
    }//GEN-LAST:event_botonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarSancion;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel campoNombreCliente;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JPanel panelSancionesCliente;
    private javax.swing.JTable tablaSanciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        campoNombreCliente.setText("Cliente: " + cliente.toString());
        ((SancionTableModel) tablaSanciones.getModel()).setSanciones(controlador.obtenerSanciones(cliente));
    }

}
