/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Mauro
 */
public class TopPeliculasUI extends javax.swing.JPanel {

    /**
     * Creates new form TopPeliculasUI
     */
    public TopPeliculasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jsp = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Top Péliculas Demandadas");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tablaPeliculas.setAutoCreateRowSorter(true);
        tablaPeliculas.setModel(new Vistas.modelos.PeliculasDemandadasTableModel());
        tablaPeliculas.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaPeliculas);

        add(jsp, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tablaPeliculas;
    // End of variables declaration//GEN-END:variables
}
